ObsidianPublisher/obsidian-mkdocs-publisher-python:
  - source: docs/en/OBS2MK - Python in terminal/usage.md
    dest: README.md
ObsidianPublisher/obsidian-github-publisher:
  - source: docs/en/Obsidian Github Publisher/index.md
    dest: README.md
  - source: docs/fr/Obsidian Github Publisher/index.md
    dest: docs/README_FR.md
ObsidianPublisher/obsidian-mkdocs-publisher-template:
  - docs/assets/css/custom_attributes
  - docs/assets/css/img-grid-floats.css
  - docs/assets/css/utils.css
  - docs/assets/js/utils.js
  - source: docs/Template - The blog/index.md
    dest: README.md
