ObsidianPublisher/obsidian-github-publisher:
  - source: docs/en/Obsidian/index.md
    dest: README.md
  - source: docs/fr/Obsidian/index.md
    dest: docs/README_FR.md
ObsidianPublisher/obsidian-mkdocs-publisher-template:
  - docs/assets/css/custom_attributes
  - docs/assets/css/img-grid-floats.css
  - docs/assets/css/utils.css
  - docs/assets/js/utils.js
  - source: docs/en/Getting Started/configuration.md
    dest: README.md
  - source: docs/fr/Getting Started/configuration.md
    dest: README-FR.md