obsidianMkdocs/obsidian-mkdocs-publisher-python:
  - source: docs/documentation/obs2mk/usage.md
    dest: README.md
obsidianMkdocs/obsidian-github-publisher:
  - source: docs/documentation/Obsidian Github Publisher.md
    dest: README.md
Mara-li/Seed_publish:
  - .github/workflows/ci.yml
  - .github/workflows/mkdocs_build.yml
obsidianMkdocs/obsidian-mkdocs-publisher-template:
  - .github/workflows/ci.yml
  - .github/workflows/mkdocs_build.yml
  - docs/assets/css/custom_attributes
  - docs/assets/css/img-grid-floats.css
  - docs/assets/css/utils.css
  - docs/assets/js/utils.js
  - source: docs/documentation/create the blog.md
    dest: README.md
