obsidianMkdocs/obsidian-mkdocs-publisher-python:
  - source: docs/OBS2MK - Python in terminal/usage.md
    dest: README.md
obsidianMkdocs/obsidian-github-publisher:
  - source: docs/Obsidian Github Publisher/index.md
    dest: README.md
obsidianMkdocs/obsidian-mkdocs-publisher-template:
  - .github/workflows/ci.yml
  - .github/workflows/mkdocs_build.yml
  - docs/assets/css/custom_attributes
  - docs/assets/css/img-grid-floats.css
  - docs/assets/css/utils.css
  - docs/assets/js/utils.js
  - source: docs/Template - The blog/index.md
    dest: README.md
