group:
  - files: 
    - docs/assets/css/custom_attributes.css
    - docs/assets/css/customization.css
    - source: docs/en/Getting Started/configuration.md
      dest: README.md
    repos: |
      ObsidianPublisher/publisher-template-gh-pages
      ObsidianPublisher/publisher-template-netlify
  - files:
    - source: docs/Obsidian/index.md
      dest: README.md
    - source: docs/Obsidian/index.md
      dest: docs/README.md
    - source: docs/Obsidian/Developping.md
      dest: docs/DEVELOPPING.md
    - source: docs/Obsidian/Commands.md
      dest: docs/COMMANDS.md
    repos: |
      ObsidianPublisher/obsidian-github-publisher
  - files:
    - source: .github/workflows/update_requirements.yml
      dest: .github/workflows/update_requirements.yml
    - source: requirements.txt
      dest: requirements.txt
    repos: |
      ObsidianPublisher/publisher-template-netlify
