name: Publisher
channels:
  - conda-forge
  - defaults
dependencies:
  - _ipython_minor_entry_point
  - asttokens
  - backcall
  - backports
  - backports.functools_lru_cache
  - bzip2
  - ca-certificates
  - colorama
  - debugpy
  - decorator
  - entrypoints
  - executing
  - ipykernel
  - ipython
  - jedi
  - jupyter_client
  - jupyter_core
  - libffi
  - libsodium
  - libsqlite
  - libzlib
  - matplotlib-inline
  - nest-asyncio
  - openssl
  - packaging
  - parso
  - pickleshare
  - pip
  - prompt-toolkit
  - psutil
  - pure_eval
  - pyparsing
  - python
  - python-dateutil
  - python_abi
  - pyzmq
  - setuptools
  - six
  - sqlite
  - stack_data
  - tk
  - tornado
  - traitlets
  - ucrt
  - vc
  - vs2015_runtime
  - wcwidth
  - wheel
  - xz
  - zeromq
  - pip:
    - astroid
    - attrs
    - autoflake
    - autopep8
    - babel
    - beautifulsoup4
    - black
    - bleach
    - bracex
    - cairocffi
    - cairosvg
    - certifi
    - cffi
    - charset-normalizer
    - click
    - contourpy
    - cssselect2
    - cycler
    - defusedxml
    - dill
    - docformatter
    - drawio
    - editorconfig
    - fastjsonschema
    - fonttools
    - ghp-import
    - gitdb
    - gitpython
    - html2text
    - idna
    - imgkit
    - importlib-metadata
    - importlib-resources
    - isort
    - jinja2
    - jsbeautifier
    - jsonpickle
    - jsonschema
    - jupyterlab-pygments
    - jupytext
    - kiwisolver
    - lazy-object-proxy
    - lxml
    - markdown
    - markdown-it-py
    - markupsafe
    - matplotlib
    - mccabe
    - mdit-py-plugins
    - mdurl
    - mdx-breakless-lists
    - mdx-wikilink-plus
    - mergedeep
    - mistune
    - mkdocs
    - mkdocs-awesome-pages-plugin
    - mkdocs-callouts
    - mkdocs-custom-fences
    - mkdocs-custom-tags-attributes
    - mkdocs-encryptcontent-plugin
    - mkdocs-ezlinked-plugin
    - mkdocs-git-revision-date-localized-plugin
    - mkdocs-glightbox
    - mkdocs-material
    - mkdocs-material-extensions
    - mkdocs-mermaid2-plugin
    - mkdocs-meta-descriptions-plugin
    - mkdocs-preview-links-plugin
    - mkdocs-simple-hooks
    - mkdocs-static-i18n
    - mypy-extensions
    - natsort
    - nbclient
    - nbconvert
    - nbformat
    - networkx
    - numpy
    - obsidiantools
    - pandas
    - pandocfilters
    - pathspec
    - pillow
    - pkgutil-resolve-name
    - platformdirs
    - pur
    - pycodestyle
    - pycparser
    - pycryptodome
    - pyflakes
    - pyformat
    - pygments
    - pygtrie
    - pylint
    - pymdown-extensions
    - pyrsistent
    - python-frontmatter
    - pytz
    - pyvis
    - pywin32
    - pyyaml
    - pyyaml-env-tag
    - regex
    - requests
    - smmap
    - soupsieve
    - tinycss2
    - toml
    - tomli
    - tomlkit
    - typing-extensions
    - unify
    - untokenize
    - urllib3
    - watchdog
    - wcmatch
    - webencodings
    - wrapt
    - yapf
    - zipp
